# The different Materials to look for within the mine structure.
spawnPoint: "CHEST"
mineCorner: "POWERED_RAIL"
sellNpc: "WHITE_WOOL"
debugMode: false

mineTypes:
  Test:
    file: "structure.dat"
    priority: 1
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    allowFlags:
      - "block-break"
    denyFlags:
      - "block-place"
  Test2:
    file: "structure2.dat"
    priority: 2
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    allowFlags:
      - "block-break"
    denyFlags:
      - "block-place"
  Test3:
    file: "structure3.dat"
    priority: 3
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    allowFlags:
      - "block-break"
    denyFlags:
      - "block-place"