# The different Materials to look for within the mine structure.
spawnPoint: "CHEST"
mineCorner: "POWERED_RAIL"
sellNpc: "WHITE_WOOL"

mineTypes:
  Test:
    file: "structure.dat"
    priority: 1
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
  Test2:
    file: "structure.dat"
    priority: 2
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
  Test3:
    file: "structure.dat"
    priority: 3
    resetTime: 5
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1